name: Release
on:
  release:

jobs:
  test:
    name: cargo publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
